# SwiftLint Configuration for TenX
# https://github.com/realm/SwiftLint

# Paths to ignore
excluded:
  - .build
  - TenX.xcodeproj
  - TenXShared/.build
  - DerivedData
  - Pods
  - Carthage

# Disabled rules (too noisy or not applicable)
disabled_rules:
  - line_length                    # Modern screens are wide
  - trailing_whitespace            # Handled by SwiftFormat
  - opening_brace                  # Handled by SwiftFormat
  - statement_position             # Handled by SwiftFormat
  - todo                           # Allow TODOs during development
  - nesting                        # SwiftUI views often nest deeply

# Opt-in rules (good practices)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

# Rule configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

large_tuple:
  warning: 3
  error: 4

# Force cast/try are sometimes necessary
force_cast:
  severity: warning

force_try:
  severity: warning

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use os_log or Logger instead of print"
    severity: warning
    match_kinds:
      - identifier
