name: TenX
options:
  bundleIdPrefix: com.matthewlam
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    DEVELOPMENT_TEAM: P2MBURJVUW
packages:
  TenXShared:
    path: Shared

targets:
  TenX:
    type: application
    platform: iOS
    sources:
      - App
    resources:
      - App/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.tenx
        INFOPLIST_FILE: App/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/TenX.entitlements
    dependencies:
      - package: TenXShared
      - target: TenXWidgets

  TenXWidgets:
    type: app-extension
    platform: iOS
    sources:
      - Widgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.tenx.widgets
        INFOPLIST_FILE: Widgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: Widgets/TenXWidgets.entitlements
    dependencies:
      - package: TenXShared

  TenXTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.tenx.tests
    dependencies:
      - target: TenX

  TenXUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.tenx.uitests
    dependencies:
      - target: TenX

schemes:
  TenX:
    build:
      targets:
        TenX: all
    run:
      config: Debug
    test:
      targets:
        - TenXTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
