name: TenX
options:
  bundleIdPrefix: com.matthewlam
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.2"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: 5.9
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  TenXShared:
    path: TenXShared

targets:
  TenX:
    type: application
    platform: iOS
    sources:
      - TenXApp
    resources:
      - TenXApp/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.tenx
        INFOPLIST_FILE: TenXApp/Resources/Info.plist
        ENTITLEMENTS_FILE: TenXApp/TenX.entitlements
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint lint --config "${SRCROOT}/.swiftlint.yml"
          else
            echo "warning: SwiftLint not installed. Run 'brew install swiftlint'"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - package: TenXShared
      - target: TenXWidgets

  TenXWidgets:
    type: app-extension
    platform: iOS
    sources:
      - TenXWidgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matthewlam.tenx.widgets
        INFOPLIST_FILE: TenXWidgets/Info.plist
        ENTITLEMENTS_FILE: TenXWidgets/TenXWidgets.entitlements
    dependencies:
      - package: TenXShared

  TenXTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TenXTests
    dependencies:
      - target: TenX

  TenXUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - TenXUITests
    dependencies:
      - target: TenX
